const initialState = [
  {
    id: 1,
    name: 'Husan',
    email: 'qwerty@gmail.com',
    number: 2345109876,
    departament: 'Development',
    count: 1,
  },
  {
    id: 2,
    name: 'Ali',
    email: 'ytrewq@gmail.com',
    number: 8765432109,
    departament: 'Marketing',
    count: 3,
  },
  {
    id: 3,
    name: 'Jamoliddin',
    email: 'werty@gmail.com',
    number: 7654321890,
    departament: 'HR',
    count: 6,
  },
  {
    id: 4,
    name: 'Hasan',
    email: 'zxcvb@gmail.com',
    number: 3214567890,
    departament: 'Accounting',
    count: 4,
  },
  {
    id: 5,
    name: 'Akbarali',
    email: 'dfghj@gmail.com',
    number: 5432167890,
    departament: 'Marketing',
    count: 1,
  },
  {
    id: 6,
    name: 'Tursunboy',
    email: 'poiuy@gmail.com',
    number: 9087654321,
    departament: 'HR',
    count: 10,
  },
  {
    id: 7,
    name: 'Joraqul',
    email: 'asdfg@gmail.com',
    number: 9087654321,
    departament: 'Accounting',
    count: 1,
  },
]

export default initialState